name: "Soar Datamap Validation"
description: "Validate Soar project code against its datamap using VisualSoar"
author: "Nathan Glenn"
branding:
  icon: "check-circle"
  color: "blue"
inputs:
  projectPath:
    description: "Path to the Soar project file to validate."
    required: true
  outputPath:
    description: "Path to the output file for validation results."
    required: false
    default: "${{ runner.temp }}/visualsoar_dm_validation_log.jsonl"
outputs:
  outputPath:
    description: "The path to the output file for validation results."
    value: ${{ inputs.outputPath }}
runs:
  using: "composite"
  steps:
    - name: Checkout VisualSoar
      uses: actions/checkout@v3
      with:
        repository: "SoarGroup/VisualSoar"
        path: "external/VisualSoar"

    - name: Report VisualSoar Version and Git SHA
      shell: bash
      run: |
        cd "external/VisualSoar"
        ./gradlew properties -q | grep "version:" > visualsoar_version.txt
        echo "VisualSoar version: $(cat visualsoar_version.txt)"
        git rev-parse HEAD > visualsoar_git_sha.txt
        echo "VisualSoar git sha: $(cat visualsoar_git_sha.txt)"

    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"

    - name: Run Datamap Validation
      shell: bash
      run: |
        cd "external/VisualSoar"
        abs_project_path="${{ github.workspace }}/${{ inputs.projectPath }}"
        ./gradlew run --quiet --args="--check productionsAgainstDatamap --project \"$abs_project_path\" --json" | tee "${{ inputs.outputPath }}"
        gradle_exit_code=${PIPESTATUS[0]}
        if [ ! -f "${{ inputs.outputPath }}" ]; then
          echo "Error: visualsoar_dm_validation_log.jsonl was not created."
          exit 1
        fi
        echo "Gradle exit code: $gradle_exit_code"
        exit $gradle_exit_code

    - name: Annotate with Validation Results
      if: failure()
      shell: bash
      run: |
        ${{ github.action_path }}/parse_diagnostics.sh < "${{ inputs.outputPath }}"

    - name: Validation Passed
      if: success()
      shell: bash
      run: |
        echo "Datamap validation completed successfully for project: ${{ inputs.projectPath }}"

    # Remove the VisualSoar folder after the action completes
    # to avoid cluttering the client workspace with unnecessary files.
    - name: Cleanup VisualSoar Folder
      if: always()
      shell: bash
      run: |
        echo "Cleaning up VisualSoar folder..."
        rm -rf "external/VisualSoar"
        echo "Cleanup completed."
