name: "Run VisualSoar Datamap Validation"
description: "Validate Soar project code against its datamap using VisualSoar"
author: "Nathan Glenn"
inputs:
  projectPath:
    description: "Path to the Soar project file to validate."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout VisualSoar
      uses: actions/checkout@v3
      with:
        repository: "YourUsername/VisualSoar"
        path: "VisualSoar"

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: "11"

    - name: Run Datamap Validation
      shell: bash
      run: |
        cd VisualSoar
        ./gradlew run --args="--check productionsAgainstDatamap --project ${{ inputs.projectPath }}" | tee visualsoar_dm_validation_log.log
        gradle_exit_code=${PIPESTATUS[0]}
        exit $gradle_exit_code

    - name: Check Datamap Validation Result
      if: failure()
      shell: bash
      run: |
        # Iterate over each line in the output file and create an error annotation
        while IFS= read -r line; do
          # Skip empty lines
          if [[ -n "$line" ]]; then
            echo "::error::$line"
          fi
        done < visualsoar_dm_validation_log.log

    - name: Upload Validation Log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: visualsoar_dm_validation_log_log
        path: visualsoar_dm_validation_log.log

    - name: Validation Passed
      if: success()
      shell: bash
      run: echo "Datamap validation completed successfully!"
